### ISSUE TITLE
Warrior Talent - Blood Craze incorrect tooltip

### ISSUE THREAD

**Issue by Malorh** [hseager/Classic-WoW-Talent-Planner#12]
Blood Craze (Warrior, Fury, tier 3) is listed with values 2%/6%/12%, but it should be 1%/2%/3%.

Here's a wiki page if you don't remember the 1%/2%/3% values and want to verify it: https://vanilla-wow.fandom.com/wiki/Blood_Craze

I normally use GitLab, but I really can't find the tags here in GitHub, so I can't tag this issue as "bug", sorry.

**Comment by hseager** [comment]
Looks like it was changed in patch 1.5.0 to 1%/2%/3% which might be why the wowhead calculator gets it wrong!

https://wowwiki.fandom.com/wiki/Blood_Craze

Just put in a fixed for this, thanks for raising
