### ISSUE TITLE
Druid Talent - Improved Regrowth incorrect tooltip

### ISSUE THREAD

**Issue by Malorh** [hseager/Classic-WoW-Talent-Planner#13]
Improved Regrowth (Druid, Restroration, tier 6) shows the tooltip for Improved Tranquility (tier 5).

The tooltip should read **Increases the critical effect chance of your Regrowth spell by 10%/20%/30%/40%/50%**.

**Comment by hseager** [comment]
Thanks for raising

**Comment by Malorh** [comment]
@hseager You closed this a week ago, but just for the record; the error still exists on the live version. However, I see that there is a correct tooltip in the *talent-data.json* file. I tried to close my browser and clear the internet cache with CCleaner, but this didn't help.

Maybe something links to the incorrect tooltip (i.e. two items links to Improved Tranquility instead of one to that and another one to Improved Regrowth)? I don't know how you have written the code, and I don't feel like checking right now :)

**Comment by hseager** [comment]
You will probably need to delete your local storage if you've saved the trees in the past. Cheers
