### ISSUE TITLE
Rogue Serrated Blades values scales with level

### ISSUE THREAD

**Issue by hseager** [hseager/Classic-WoW-Talent-Planner#16]
From Navashed:
> it would be cool if the value changed dynamically based on what level the user is (aka how many points they've spent)

**Comment by Navashed** [comment]
Serrated Blades should penetrate 1.67/3.33/5 armor per level. This comes to 100/200/300 armor at level 60.

**Comment by Malorh** [comment]
I think it would be nice for the tooltip to always show the level 60 values as well. Either in parenthesis or in a line below all the normal text.

**Comment by hseager** [comment]
This should be live now, let me know if you see any issues with it! Cheers
