### ISSUE TITLE
Side arrow is always enabled

### ISSUE THREAD

**Issue by Iturio** [hseager/Classic-WoW-Talent-Planner#2]
The side arrow of depending talents is always displayed as "is-enabled", even if the prequisit (depending talent) hasn't been skilled yet.

![side-arrow](https://user-images.githubusercontent.com/39367923/57217702-a2c3fc80-6ff3-11e9-8fe6-619752ae25f4.jpg)

**Comment by hseager** [comment]
This was actually a CSS issue, so a nice easy fix! Thanks for raising
