### ISSUE TITLE
Hunter Talent - Bestial Wrath incorrect

### ISSUE THREAD

**Issue by Iturio** [hseager/Classic-WoW-Talent-Planner#3]
The last talent in the BM tree (Bestial Wrath) should need 30 talent points spent in the BM tree, instead of 25.

![bestial-wrath](https://user-images.githubusercontent.com/39367923/57218186-013daa80-6ff5-11e9-801d-76da26c0f5de.jpg)

**Comment by hseager** [comment]
Thanks for raising this
