### ISSUE TITLE
Mage Talent - Arcane Meditation has incorrect number of levels

### ISSUE THREAD

**Issue by Malorh** [hseager/Classic-WoW-Talent-Planner#7]
The Mage talent Arcane Meditation (tier 4) is shown to have five levels, but it should only have three levels.
The tooltip stops at three (as it should).

**Comment by Malorh** [comment]
I think you just need to change
> 	"maxRank": 5, 

to
> 	"maxRank": 3, 

in line 5055 in talent-data.json.

**Comment by hseager** [comment]
Thanks for looking into this! Fixed, and will deploy to live later this evening
