### ISSUE TITLE
[Suggestion] Reset Individual Trees

### ISSUE THREAD

**Issue by Malorh** [hseager/Classic-WoW-Talent-Planner#8]
It would be nice to be able to reset individual trees, e.g. going from "20/0/31" to "0/0/31" with the push of one button instead of right-clicking on 20 talents.
The buttons could be next to the title of the tree, e.g. "Arms (20)     [reset]".
Alternative to a text "reset": maybe just a red cross.

**Comment by hseager** [comment]
I've added a reset button for each tree rather than one for all of them. Seems to work okay with the talent path at the bottom too which is good.
